[package]
name = "tf-inceptionv3"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
license = "MIT/Apache-2.0"

[dependencies]
image = "0.23"
tract-tensorflow = { path = "../../tensorflow" }

[features]
conform = [ "tract-tensorflow/conform" ]

[dev-dependencies]
criterion = "0.3"
dinghy-test = "0.4"
env_logger = "0.8"
log = "0.4"

[[bench]]
harness = false
name = "inceptionv3"
